In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv

In [6]:
df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [9]:
df=df.sample(10000)

In [10]:
df.shape

(10000, 2)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 5957 to 6813
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [12]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [13]:
df.head()

                                                  review  sentiment
5957   There is no way to describe how really, really...          0
28832  There's a legion of Mick Garris haters out the...          1
23605  Finally I got to see the infamous "Ice Age". A...          1
33537  The Brain (or head) that Wouldn't Die is one o...          0
9731   This was a riveting film, one that really drew...          1

In [14]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'Finally I got to see the infamous "Ice Age". Apart from maybe not being as dead funny as I\'d hoped for after seeing the brilliant teaser there is not a bad word I can say about it. Sure, it\'s not as glamorous as a Disney production(besides, it is Fox\'s 1st attempt at a full length CG movie) but it\'s got immense heart and on some occasions(like the look in Manfred\'s eyes after we see the sad glimpse of his past) I found myself on the verge of tears. But when they reunited the baby with its father I just couldn\'t hold them in anymore. A movie that has no trouble walking on the thin line of sappy and cliché and manages to bring more than the best out of it; the end result being one of the most touching animated creations I have ever seen. Great funny looking characters that quickly grow on you(and great voice talents as well) and many funny memorable scenes, especially from Scrat\'s behalf make the movie more than enough reason to give it a go. Plus the Dodo scene, which is my personal favorite funny scene of 2002.I honestly don\'t get it, but for some reason it really looks like CG animation will be taking the upper hand in the future. But if it just means that there will be more movies like this one (and who can forget Pixar\'s creations) then I don\'t really mind, at least for now. 9/10'

In [15]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [16]:
df['review']=df['review'].apply(clean_html)

In [17]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [18]:
df['review']=df['review'].apply(convert_lower)

In [19]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [20]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [21]:
df['review']=df['review'].apply(remove_special)

In [22]:
# Remove the stop words
import nltk

In [23]:
from nltk.corpus import stopwords

In [24]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [25]:
df

                                                  review  sentiment
5957   there is no way to describe how really  really...          0
28832  there s a legion of mick garris haters out the...          1
23605  finally i got to see the infamous  ice age   a...          1
33537  the brain  or head  that wouldn t die is one o...          0
9731   this was a riveting film  one that really drew...          1
...                                                  ...        ...
21462  i read a viciously hidden remarks on a previou...          1
49598  officially the first martial arts movie in uss...          0
2210   one of the better movies to come out of the 19...          1
47110  some people say this is the best film that prc...          1
6813   this is your only spoiler warning  what a sad ...          0

[10000 rows x 2 columns]

In [26]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [27]:
df['review']=df['review'].apply(remove_stopwords)

In [28]:
df

                                                  review  sentiment
5957   [way, describe, really, really, really, bad, m...          0
28832  [legion, mick, garris, haters, feel, direct, h...          1
23605  [finally, got, see, infamous, ice, age, apart,...          1
33537  [brain, head, die, one, thoughtful, low, budge...          0
9731   [riveting, film, one, really, drew, big, fan, ...          1
...                                                  ...        ...
21462  [read, viciously, hidden, remarks, previous, c...          1
49598  [officially, first, martial, arts, movie, ussr...          0
2210   [one, better, movies, come, 1980, based, fact,...          1
47110  [people, say, best, film, prc, ever, released,...          1
6813   [spoiler, warning, sad, state, cinema, unprofe...          0

[10000 rows x 2 columns]

In [29]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [30]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [31]:
stem_words(['I','loved','loving','it'])

['I', 'love', 'love', 'it']

In [32]:
df['review']=df['review'].apply(stem_words)

In [33]:
df

                                                  review  sentiment
5957   [way, describ, realli, realli, realli, bad, mo...          0
28832  [legion, mick, garri, hater, feel, direct, hor...          1
23605  [final, got, see, infam, ice, age, apart, mayb...          1
33537  [brain, head, die, one, thought, low, budget, ...          0
9731   [rivet, film, one, realli, drew, big, fan, wil...          1
...                                                  ...        ...
21462  [read, vicious, hidden, remark, previou, comme...          1
49598  [offici, first, martial, art, movi, ussr, cine...          0
2210   [one, better, movi, come, 1980, base, fact, mo...          1
47110  [peopl, say, best, film, prc, ever, releas, su...          1
6813   [spoiler, warn, sad, state, cinema, unprofessi...          0

[10000 rows x 2 columns]

In [34]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [35]:
df['review']=df['review'].apply(join_back)

In [36]:
df['review']

5957     way describ realli realli realli bad movi sham...
28832    legion mick garri hater feel direct horror fil...
23605    final got see infam ice age apart mayb dead fu...
33537    brain head die one thought low budget exploit ...
9731     rivet film one realli drew big fan william h m...
                               ...
21462    read vicious hidden remark previou comment sta...
49598    offici first martial art movi ussr cinematogra...
2210     one better movi come 1980 base fact movi tell ...
47110    peopl say best film prc ever releas sure sinc ...
6813     spoiler warn sad state cinema unprofession jun...
Name: review, Length: 10000, dtype: object

In [37]:
X=df.iloc[:,0:1].values

In [38]:
X.shape

(10000, 1)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [40]:
X=cv.fit_transform(df['review']).toarray()

In [41]:
X.shape

(10000, 2500)

In [42]:
X[0].mean()

0.0416

In [43]:
y=df.iloc[:,-1].values

In [44]:
y.shape

(10000,)

In [45]:
# X,y
# Training set
# Test Set(Already know the result)

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [47]:
X_train.shape

(8000, 2500)

In [48]:
X_test.shape

(2000, 2500)

In [49]:
y_train.shape

(8000,)

In [50]:
y_test.shape

(2000,)

In [51]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [52]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [53]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [54]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [55]:
y_test.shape

(2000,)

In [56]:
y_pred1.shape

(2000,)

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.7355
Multinomial 0.838
Bernaulli 0.854